### PR TITLE
Fixed deadlock on startup

### LINKED ISSUE #1: bluepot interface doesn't work in debian jessie
Hi
Trying to start bluepot in debian jessie gives a completely blank interface.
bluepot is currently in kali linux. And a future release (kali-roling) will be based on debian Jessie.
The bug has been reported here with more details:
https://bugs.kali.org/view.php?id=2177
(we have exactly same results with debian jessie and kali-rolling)

Do you have any idea how to fix that?

thanks

### PR DESCRIPTION
**Pull request by lem-solutions**
Fixes #1

### CODE REVIEW

**Comment by andrewmichaelsmith** [comment]
Thank you for this! 

I'll need to dust off the environment I ran this in - so please forgive my slowness - but can you clarify what `activation-1.1.1.jar ` is for?

**Comment by lem-solutions** [comment]
`javax.activation` was deprecated in java 9 and removed in 11. But it is still available as this standalone jar file. see https://stackoverflow.com/questions/46493613/what-is-the-replacement-for-javax-activation-package-in-java-9

**Comment by andrewmichaelsmith** [comment]
@lem-solutions - sorry I've been slow! I've tried this and get to start the application:

```
$ java -jar bluepot.jar 
ALL:Attempting to initialize bluetooth devices
BlueCove log redirected to log4j
log4j:WARN No appenders could be found for logger (com.intel.bluetooth).
log4j:WARN Please initialize the log4j system properly.
BlueCove version 2.1.0 on bluez
ALL:Sensors initialized
ALL:Loaded sensor configuration
ALL:Starting system..
```

But I'm still getting a blank screen:

image

Have you witnessed this behaviour?

**Comment by lem-solutions** [comment]
try running it as root, I forgot to mention, It used to use gksudo to aquire root privileges but gksudo is gone in modern systems(for good reason). It needs to be run as root to stop bluetoothd and re-run it in compatibility mode

**Comment by andrewmichaelsmith** [comment]
D'oh, I was sure I had but apparently not! Thanks!

**Comment by andrewmichaelsmith** [comment]
@lem-solutions - I put a bounty on this years ago, it's still there if you'd like to claim (please do!): https://www.bountysource.com/issues/12486899-bluepot-interface-doesn-t-work-in-debian-jessie?show_profile_modal=1

**Comment by lem-solutions** [comment]
thank you

**Pull request merged**
